import { Bot, ChevronRight, Lock, X } from "lucide-react";
import { useState } from "react";
import { loginAccount, registerAccount } from "../api";

export function AuthModal({ onClose, onAuthenticated, onDemo }: { onClose: () => void; onAuthenticated: () => Promise<void>; onDemo: () => void }) {
  const [mode, setMode] = useState<"register" | "login">("register"); const [name, setName] = useState("Кирилл"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState<string>();
  async function submit(event: React.FormEvent) { event.preventDefault(); setPending(true); setError(undefined); try { if (mode === "register") await registerAccount({ displayName: name, email, password }); else await loginAccount({ email, password }); await onAuthenticated(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось войти"); } finally { setPending(false); } }
  return <div className="modal-backdrop"><form className="auth-modal" onSubmit={submit}><button type="button" className="modal-close" onClick={onClose}><X /></button><div className="brand auth-brand"><span className="brand-mark"><Bot /></span>TMA Studio</div><h2>{mode === "register" ? "Создайте первый проект" : "С возвращением"}</h2><p>{mode === "register" ? "Конструктор бесплатный. Оплата понадобится только перед запуском." : "Войдите, чтобы продолжить работу."}</p>{mode === "register" && <label><span>Ваше имя</span><input required value={name} onChange={(e) => setName(e.target.value)} /></label>}<label><span>Email</span><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" /></label><label><span>Пароль</span><input required minLength={12} type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Минимум 12 символов" /><small><Lock />Пароль защищён scrypt-хешированием</small></label>{error && <div className="auth-error">{error}</div>}<button className="primary-button auth-submit" disabled={pending}>{pending ? "Подождите…" : mode === "register" ? "Создать бесплатно" : "Войти"}<ChevronRight /></button><button type="button" className="auth-switch" onClick={() => setMode(mode === "register" ? "login" : "register")}>{mode === "register" ? "Уже есть аккаунт? Войти" : "Нет аккаунта? Зарегистрироваться"}</button><div className="demo-divider"><span>или</span></div><button type="button" className="outline-button demo-button" onClick={onDemo}>Открыть демо без регистрации</button></form></div>;
}
