import { ArrowDown, ArrowLeft, ArrowUp, Box, ChevronDown, Eye, FileText, GripVertical, Heading1, Image, LayoutGrid, MessageSquareText, MousePointerClick, Pencil, Plus, Redo2, Rocket, Send, ShoppingBag, SlidersHorizontal, Smartphone, Trash2, Undo2, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { deleteRemotePage, hasSession, saveRemoteProject } from "../api";
import { createBlock, saveProject } from "../store";
import { useCompact } from "../use-compact";
import type { BlockAction, BlockType, BuilderBlock, BuilderPage, BuilderTab, FormField, ProjectState } from "../types";
import { PhonePreview } from "./PhonePreview";

const blockCatalog: Array<{ type: BlockType; title: string; icon: typeof Heading1 }> = [
  { type: "heading", title: "Заголовок", icon: Heading1 }, { type: "text", title: "Текст", icon: MessageSquareText }, { type: "button", title: "Кнопка", icon: MousePointerClick }, { type: "media", title: "Картинка", icon: Image }, { type: "product", title: "Товар", icon: ShoppingBag }, { type: "form", title: "Форма", icon: Send },
];

export function Builder({ initialProject, onChange, onBack, onPreview, onLaunch, onMessage }: { initialProject: ProjectState; onChange: (project: ProjectState) => void; onBack: () => void; onPreview: (project: ProjectState) => void; onLaunch: (project: ProjectState) => void; onMessage: (message: string) => void }) {
  const [project, setProject] = useState(initialProject);
  const [selectedId, setSelectedId] = useState<string | undefined>(initialProject.pages[0]?.blocks[0]?.id);
  const [theme, setTheme] = useState<"light" | "dark">("light");
  const [tab, setTab] = useState<BuilderTab>("blocks");
  const compact = useCompact();
  const [sheet, setSheet] = useState<"none" | "pages" | "inspector">("none");
  const [history, setHistory] = useState<ProjectState[]>([]);
  const [future, setFuture] = useState<ProjectState[]>([]);
  const [saveState, setSaveState] = useState<"saved" | "saving" | "error">("saved");
  const firstRender = useRef(true);
  const skipNextSave = useRef(false);
  const activePage = project.pages.find((item) => item.id === project.activePageId) ?? project.pages[0];
  const selected = activePage?.blocks.find((block) => block.id === selectedId);
  useEffect(() => { if (initialProject.id !== project.id || (initialProject.updatedAt && initialProject.updatedAt !== project.updatedAt)) { skipNextSave.current = true; setProject(initialProject); setSelectedId(initialProject.pages[0]?.blocks[0]?.id); } }, [initialProject.id, initialProject.updatedAt]);

  const commit = useCallback((change: (current: ProjectState) => ProjectState) => {
    setProject((current) => { const next = { ...change(current), previewed: false, hasPendingChanges: current.status === "active" ? true : current.hasPendingChanges }; if (next === current) return current; setHistory((items) => [...items.slice(-49), current]); setFuture([]); setSaveState("saving"); return next; });
  }, []);
  useEffect(() => {
    if (firstRender.current) { firstRender.current = false; return; }
    if (skipNextSave.current) { skipNextSave.current = false; return; }
    saveProject(project); onChange(project);
    if (!hasSession()) { setSaveState("saved"); return; }
    const timer = setTimeout(() => { setSaveState("saving"); void saveRemoteProject(project).then((saved) => { skipNextSave.current = true; setProject(saved); saveProject(saved); onChange(saved); setSaveState("saved"); }).catch((reason) => { setSaveState("error"); onMessage(reason instanceof Error ? reason.message : "Не удалось сохранить проект"); }); }, 900);
    return () => clearTimeout(timer);
  }, [project, onChange, onMessage]);

  const savedLabel = useMemo(() => saveState === "saving" ? "Сохраняем в облаке…" : saveState === "error" ? "Ошибка сохранения — повторите" : hasSession() ? "Сохранено в облаке" : "Сохранено на этом устройстве", [saveState]);
  function pageChange(change: (page: BuilderPage) => BuilderPage) { if (!activePage) return; commit((current) => ({ ...current, pages: current.pages.map((page) => page.id === activePage.id ? change(page) : page) })); }
  function setBlocks(blocks: BuilderBlock[]) { pageChange((page) => ({ ...page, blocks })); }
  function addBlock(type: BlockType) { const block = createBlock(type); setBlocks([...(activePage?.blocks ?? []), block]); setSelectedId(block.id); if (compact) setSheet("inspector"); }
  function updateSelected(next: BuilderBlock) { if (!activePage) return; setBlocks(activePage.blocks.map((block) => block.id === next.id ? next : block)); }
  function removeSelected() { if (!selected || !activePage) return; setBlocks(activePage.blocks.filter((block) => block.id !== selected.id)); setSelectedId(undefined); }
  function moveSelected(direction: -1 | 1) { if (!selected || !activePage) return; const index = activePage.blocks.findIndex((item) => item.id === selected.id); const nextIndex = index + direction; if (nextIndex < 0 || nextIndex >= activePage.blocks.length) return; const blocks = [...activePage.blocks]; [blocks[index], blocks[nextIndex]] = [blocks[nextIndex]!, blocks[index]!]; setBlocks(blocks); }
  function undo() { const previous = history.at(-1); if (!previous) return; setFuture((items) => [project, ...items].slice(0, 50)); setHistory((items) => items.slice(0, -1)); setProject({ ...previous, previewed: false, hasPendingChanges: previous.status === "active" ? true : previous.hasPendingChanges }); setSaveState("saving"); }
  function redo() { const next = future[0]; if (!next) return; setHistory((items) => [...items, project].slice(-50)); setFuture((items) => items.slice(1)); setProject({ ...next, previewed: false, hasPendingChanges: next.status === "active" ? true : next.hasPendingChanges }); setSaveState("saving"); }
  function addPage() { const index = project.pages.length + 1; const page: BuilderPage = { id: crypto.randomUUID(), title: `Страница ${index}`, slug: `page-${index}-${crypto.randomUUID().slice(0, 4)}`, blocks: [] }; commit((current) => ({ ...current, pages: [...current.pages, page], activePageId: page.id })); setSelectedId(undefined); setTab("blocks"); }
  async function removePage(page: BuilderPage) { if (project.pages.length === 1) { onMessage("В проекте должна остаться хотя бы одна страница"); return; } if (page.remoteRevision !== undefined) { try { await deleteRemotePage(project.id, page.id); } catch (reason) { onMessage(reason instanceof Error ? reason.message : "Не удалось удалить страницу"); return; } } commit((current) => ({ ...current, pages: current.pages.filter((item) => item.id !== page.id), activePageId: current.pages.find((item) => item.id !== page.id)?.id })); setSelectedId(undefined); }
  function addSection(kind: "hero" | "lead" | "product") { const blocks = kind === "hero" ? [createBlock("heading"), createBlock("text"), createBlock("button")] : kind === "product" ? [createBlock("heading"), createBlock("product")] : [createBlock("heading"), createBlock("text"), createBlock("form")]; setBlocks([...(activePage?.blocks ?? []), ...blocks]); setSelectedId(blocks[0]?.id); setTab("blocks"); if (compact) setSheet("inspector"); }
  function selectPage(pageId: string) { setSheet("none"); const next = { ...project, activePageId: pageId }; skipNextSave.current = true; setProject(next); saveProject(next); onChange(next); setSelectedId(undefined); }
  function renameProject() { const name = prompt("Название проекта", project.name)?.trim(); if (name) commit((current) => ({ ...current, name })); }
  function renamePage(page: BuilderPage) { const title = prompt("Название страницы", page.title)?.trim(); if (title) commit((current) => ({ ...current, pages: current.pages.map((item) => item.id === page.id ? { ...item, title } : item) })); }

  if (!activePage) return <main className="empty-screen"><h1>В проекте нет страниц</h1><button className="primary-button" onClick={addPage}>Создать страницу</button></main>;
  const hasPaidAccess = project.status === "active" && project.plan !== "free";
  const needsReconnect = hasPaidAccess && project.botStatus !== "active";
  const isLive = hasPaidAccess && !needsReconnect;
  const launchLabel = needsReconnect ? "Переподключить" : isLive ? project.hasPendingChanges ? "Опубликовать" : "Опубликовано" : project.status === "active" ? "Продлить" : "Запустить";
  const launchDisabled = saveState === "saving" || (isLive && !project.hasPendingChanges);
  return <div className={`builder ${compact ? "compact" : ""}`}><header className="builder-top"><div><button className="icon-button" onClick={onBack} aria-label="Вернуться в кабинет"><ArrowLeft /></button><button className="project-switcher" onClick={renameProject}><span className="project-dot">{project.name.slice(0, 1).toUpperCase()}</span><span><b>{project.name}</b><small className={saveState === "error" ? "error" : ""}>{savedLabel}</small></span><ChevronDown /></button></div><div className="history-buttons"><button disabled={history.length === 0} onClick={undo} aria-label="Отменить"><Undo2 /></button><button disabled={future.length === 0} onClick={redo} aria-label="Повторить"><Redo2 /></button><span /></div><div><button className="outline-button" onClick={() => onPreview(project)}><Eye />Предпросмотр</button><button className="primary-button" disabled={launchDisabled} onClick={() => onLaunch(project)}><Rocket />{launchLabel}</button></div></header>
  <div className="builder-body"><aside className={`builder-left ${compact && sheet === "pages" ? "open" : ""}`}>{compact && <div className="sheet-top"><b>Страницы и секции</b><button className="icon-button" onClick={() => setSheet("none")} aria-label="Закрыть"><X /></button></div>}<div className="builder-tabs"><button className={tab === "blocks" ? "active" : ""} onClick={() => setTab("blocks")}><Plus />Блоки</button><button className={tab === "pages" ? "active" : ""} onClick={() => setTab("pages")}><FileText />Страницы</button><button className={tab === "sections" ? "active" : ""} onClick={() => setTab("sections")}><LayoutGrid />Секции</button></div>
    {tab === "blocks" && <div className="block-library"><span className="label">БАЗОВЫЕ БЛОКИ</span><div className="block-grid">{blockCatalog.map(({ type, title, icon: Icon }) => <button key={type} onClick={() => addBlock(type)}><span><Icon /></span>{title}</button>)}</div><span className="label">СТРУКТУРА СТРАНИЦЫ</span><div className="layer-list">{activePage.blocks.map((block) => <div className={`layer-row ${block.id === selectedId ? "active" : ""}`} key={block.id}><button onClick={() => setSelectedId(block.id)}><GripVertical /><span>{blockCatalog.find((item) => item.type === block.type)?.title}</span></button>{block.id === selectedId && <span><button onClick={() => moveSelected(-1)} aria-label="Выше"><ArrowUp /></button><button onClick={() => moveSelected(1)} aria-label="Ниже"><ArrowDown /></button></span>}</div>)}</div></div>}
    {tab === "pages" && <div className="pages-panel"><div className="panel-caption"><span>СТРАНИЦЫ</span><button onClick={addPage}><Plus />Добавить</button></div>{project.pages.map((page, index) => <div className={`page-row ${page.id === activePage.id ? "active" : ""}`} key={page.id}><button onClick={() => selectPage(page.id)}>{page.title}<small>/{page.slug}</small></button><button onClick={() => renamePage(page)} aria-label={`Переименовать ${page.title}`}><Pencil /></button>{index > 0 && <button onClick={() => void removePage(page)} aria-label={`Удалить ${page.title}`}><Trash2 /></button>}</div>)}</div>}
    {tab === "sections" && <div className="sections-panel"><span className="label">ГОТОВЫЕ СЕКЦИИ</span><button onClick={() => addSection("hero")}><b>Первый экран</b><small>Заголовок, описание и CTA</small></button><button onClick={() => addSection("lead")}><b>Сбор заявки</b><small>Описание и контактная форма</small></button><button onClick={() => addSection("product")}><b>Предложение товара</b><small>Заголовок и карточка</small></button></div>}
  </aside>
  <main className={`canvas ${theme}`}><div className="canvas-toolbar"><div><span className="viewport-label"><Smartphone />Телефон</span></div><div className="theme-toggle"><button className={theme === "light" ? "active" : ""} onClick={() => setTheme("light")}>Светлая</button><button className={theme === "dark" ? "active" : ""} onClick={() => setTheme("dark")}>Тёмная</button></div></div><PhonePreview page={activePage} projectName={project.name} selectedId={selectedId} onSelect={setSelectedId} theme={theme} /></main>
  <aside className={`inspector ${compact && sheet === "inspector" ? "open" : ""}`}>{compact && <div className="sheet-top"><b>Настройки блока</b><button className="icon-button" onClick={() => setSheet("none")} aria-label="Закрыть"><X /></button></div>}{selected ? <><div className="inspector-title"><div><span className="inspector-icon"><Box /></span><span><b>{blockCatalog.find((item) => item.type === selected.type)?.title}</b><small>Настройки блока</small></span></div><button className="icon-button danger" onClick={removeSelected} aria-label="Удалить блок"><Trash2 /></button></div><InspectorFields block={selected} pages={project.pages} update={updateSelected} /><div className="inspector-tip"><span>✦</span><p><b>Подсказка</b>Пишите коротко: Mini App чаще открывают с телефона и на мобильном интернете.</p></div></> : <div className="empty-inspector"><MousePointerClick /><h3>Выберите блок</h3><p>Нажмите на элемент в телефоне или в структуре слева.</p></div>}</aside>
  </div>{compact && <nav className="build-dock" aria-label="Что добавить на страницу">
    <div className="dock-add">
      {blockCatalog.map(({ type, title, icon: Icon }) => <button key={type} onClick={() => addBlock(type)}><span><Icon /></span>{title}</button>)}
      <button onClick={() => { setTab("pages"); setSheet("pages"); }}><span><FileText /></span>Страницы</button>
    </div>
    <button className={`dock-settings ${sheet === "inspector" ? "on" : ""}`} onClick={() => setSheet(sheet === "inspector" ? "none" : "inspector")}>
      <SlidersHorizontal />{sheet === "inspector" ? "Свернуть" : "Настройки"}
    </button>
  </nav>}</div>;
}

function InspectorFields({ block, pages, update }: { block: BuilderBlock; pages: BuilderPage[]; update: (block: BuilderBlock) => void }) {
  const patch = (props: Record<string, unknown>) => update({ ...block, props: { ...block.props, ...props } } as BuilderBlock);
  if (block.type === "heading") return <div className="fields"><Field label="Текст"><textarea value={block.props.text} onChange={(event) => patch({ text: event.target.value })} /></Field><Field label="Размер"><select value={block.props.level} onChange={(event) => patch({ level: Number(event.target.value) })}><option value="1">Большой</option><option value="2">Средний</option><option value="3">Маленький</option></select></Field><Field label="Выравнивание"><div className="segmented">{(["start", "center", "end"] as const).map((align) => <button key={align} className={block.props.align === align ? "active" : ""} onClick={() => patch({ align })}>{align === "start" ? "Слева" : align === "center" ? "Центр" : "Справа"}</button>)}</div></Field></div>;
  if (block.type === "text") return <div className="fields"><Field label="Текст"><textarea rows={7} value={block.props.markdown} onChange={(event) => patch({ markdown: event.target.value })} /></Field><Field label="Стиль"><select value={block.props.tone} onChange={(event) => patch({ tone: event.target.value })}><option value="default">Обычный</option><option value="secondary">Вторичный</option><option value="hint">Подсказка</option></select></Field></div>;
  if (block.type === "button") return <div className="fields"><Field label="Текст кнопки"><input value={block.props.label} onChange={(event) => patch({ label: event.target.value })} /></Field><ActionFields action={block.props.action} pages={pages} onChange={(action) => patch({ action })} /><Field label="Стиль"><select value={block.props.style} onChange={(event) => patch({ style: event.target.value })}><option value="primary">Основная</option><option value="secondary">Вторичная</option><option value="link">Ссылка</option><option value="danger">Опасное действие</option></select></Field><Field label="Тактильный отклик"><select value={block.props.haptic} onChange={(event) => patch({ haptic: event.target.value })}><option value="none">Без отклика</option><option value="light">Лёгкий</option><option value="medium">Средний</option><option value="heavy">Сильный</option></select></Field></div>;
  if (block.type === "media") return <div className="fields"><Field label="Ссылка на изображение"><input type="url" value={block.props.url} placeholder="https://example.com/image.jpg" onChange={(event) => patch({ url: event.target.value })} /></Field><p className="field-help">Сейчас стоит встроенный образец. Замените его публичной HTTPS-ссылкой на JPG, PNG или WebP.</p><Field label="Описание для доступности"><input value={block.props.alt} onChange={(event) => patch({ alt: event.target.value })} /></Field><Field label="Пропорции"><select value={block.props.aspectRatio} onChange={(event) => patch({ aspectRatio: event.target.value })}><option value="16:9">16:9</option><option value="4:3">4:3</option><option value="1:1">1:1</option><option value="auto">По изображению</option></select></Field></div>;
  if (block.type === "product") return <div className="fields"><Field label="Название"><input value={block.props.title} onChange={(event) => patch({ title: event.target.value })} /></Field><Field label="Описание"><textarea value={block.props.description ?? ""} onChange={(event) => patch({ description: event.target.value })} /></Field><Field label="Цена, ₽"><input type="number" min="0" step="1" value={block.props.price.amountMinor / 100} onChange={(event) => patch({ price: { ...block.props.price, amountMinor: Math.max(0, Math.round(Number(event.target.value) * 100)) } })} /></Field><Field label="Текст кнопки"><input value={block.props.cta.label} onChange={(event) => patch({ cta: { ...block.props.cta, label: event.target.value } })} /></Field><ActionFields action={block.props.cta.action} pages={pages} onChange={(action) => patch({ cta: { ...block.props.cta, action } })} /></div>;
  return <FormInspector block={block} patch={patch} />;
}

function FormInspector({ block, patch }: { block: Extract<BuilderBlock, { type: "form" }>; patch: (props: Record<string, unknown>) => void }) {
  const fields = block.props.fields;
  const updateFields = (next: FormField[]) => patch({ fields: next });
  const changeField = (index: number, next: FormField) => updateFields(fields.map((field, fieldIndex) => fieldIndex === index ? next : field));
  const moveField = (index: number, direction: -1 | 1) => { const nextIndex = index + direction; if (nextIndex < 0 || nextIndex >= fields.length) return; const next = [...fields]; [next[index], next[nextIndex]] = [next[nextIndex]!, next[index]!]; updateFields(next); };
  return <div className="fields">
    <Field label="Текст кнопки"><input value={block.props.submitLabel} onChange={(event) => patch({ submitLabel: event.target.value })} /></Field>
    <Field label="Сообщение после отправки"><textarea value={block.props.successMessage} onChange={(event) => patch({ successMessage: event.target.value })} /></Field>
    <div className="form-field-editor"><b>Поля формы</b>{fields.map((field, index) => <div className="form-field-card" key={field.id}>
      <div className="form-field-row"><input value={field.label} aria-label="Название поля" onChange={(event) => changeField(index, { ...field, label: event.target.value })} /><select value={field.kind} aria-label="Тип поля" onChange={(event) => changeField(index, makeField(field.id, event.target.value as FormField["kind"], field.label))}><option value="text">Текст</option><option value="email">Email</option><option value="phone">Телефон</option><option value="checkbox">Флажок</option><option value="select">Список</option></select><label><input type="checkbox" checked={field.required} onChange={(event) => changeField(index, { ...field, required: event.target.checked })} />Обязательное</label><span><button disabled={index === 0} onClick={() => moveField(index, -1)} aria-label="Переместить поле выше"><ArrowUp /></button><button disabled={index === fields.length - 1} onClick={() => moveField(index, 1)} aria-label="Переместить поле ниже"><ArrowDown /></button><button disabled={fields.length === 1} onClick={() => updateFields(fields.filter((_, fieldIndex) => fieldIndex !== index))} aria-label={`Удалить поле ${field.label}`}><Trash2 /></button></span></div>
      {field.kind === "text" && <label className="field-option"><input type="checkbox" checked={field.multiline} onChange={(event) => changeField(index, { ...field, multiline: event.target.checked })} />Многострочное поле</label>}
      {field.kind === "select" && <Field label="Варианты через запятую"><input value={field.options.map((option) => option.label).join(", ")} onChange={(event) => { const labels = event.target.value.split(",").map((value) => value.trim()).filter(Boolean).slice(0, 100); changeField(index, { ...field, options: (labels.length ? labels : ["Вариант"]).map((label, optionIndex) => ({ value: `option-${optionIndex + 1}`, label })) }); }} /></Field>}
    </div>)}<button className="add-field" disabled={fields.length >= 50} onClick={() => updateFields([...fields, makeField(`field-${crypto.randomUUID().slice(0, 6)}`, "text", "Новое поле")])}><Plus />Добавить поле</button></div>
  </div>;
}
function ActionFields({ action, pages, onChange }: { action: BlockAction; pages: BuilderPage[]; onChange: (action: BlockAction) => void }) { return <><Field label="Действие"><select value={action.kind} onChange={(event) => { const kind = event.target.value; onChange(kind === "page" ? { kind, pageId: pages[0]?.id ?? "" } : kind === "telegram" ? { kind, url: "tg://resolve?domain=" } : { kind: "url", url: "https://" }); }}><option value="url">Открыть сайт</option><option value="page">Перейти на страницу</option><option value="telegram">Открыть Telegram</option></select></Field>{action.kind === "page" ? <Field label="Страница"><select value={action.pageId} onChange={(event) => onChange({ kind: "page", pageId: event.target.value })}>{pages.map((page) => <option key={page.id} value={page.id}>{page.title}</option>)}</select></Field> : <Field label={action.kind === "telegram" ? "Telegram-ссылка" : "Ссылка"}><input value={action.url} placeholder={action.kind === "telegram" ? "tg://resolve?domain=username" : "https://example.com"} onChange={(event) => onChange({ ...action, url: event.target.value })} /></Field>}</>; }
function makeField(id: string, kind: FormField["kind"], label: string): FormField { if (kind === "text") return { id, kind, label, required: false, multiline: false, maxLength: 255 }; if (kind === "select") return { id, kind, label, required: false, options: [{ value: "option", label: "Вариант" }] }; return { id, kind, label, required: false }; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}</label>; }
