import { ArrowRight, Bot, CheckCircle2, ChevronRight, Circle, Eye, FileText, LayoutDashboard, MessageSquare, Paintbrush, Rocket, Settings, Users } from "lucide-react";
import type { ProjectState } from "../types";

export function Dashboard({ project, onEdit, onLaunch, onHome }: { project: ProjectState; onEdit: () => void; onLaunch: () => void; onHome: () => void }) {
  return <div className="workspace"><aside className="app-sidebar"><button className="brand bare" onClick={onHome}><span className="brand-mark"><Bot size={19} /></span>TMA Studio</button><nav><a className="active"><LayoutDashboard />Главная</a><a onClick={onEdit}><FileText />Приложение</a><a><MessageSquare />Бот</a><a><Users />Заявки</a><a><Paintbrush />Дизайн</a><a><Settings />Настройки</a></nav><div className="sidebar-plan"><span>Бесплатный план</span><div><i /><i /><i /></div><small>1 из 1 проекта</small><button onClick={onLaunch}>Запустить за 350 ₽</button></div><div className="profile"><span>К</span><div><b>Кирилл</b><small>Владелец</small></div><ChevronRight /></div></aside>
    <main className="dashboard"><header><div><span className="muted">Проекты /</span><h1>{project.name}</h1></div><button className="primary-button" onClick={onLaunch}><Rocket size={17} />Запустить</button></header><div className="status-banner"><div className="status-icon"><CheckCircle2 /></div><div><b>Отличное начало — приложение уже можно посмотреть</b><p>Пройдите ещё 2 шага, чтобы открыть его клиентам.</p></div><button onClick={onEdit}>Продолжить <ArrowRight size={16} /></button></div>
      <section className="dashboard-grid"><div className="panel checklist"><div className="panel-title"><div><span>ГОТОВНОСТЬ К ЗАПУСКУ</span><h2>3 из 5 шагов</h2></div><div className="progress-ring">60%</div></div><div className="progress-line"><i /></div><Task done title="Проект создан" text="Название и базовые настройки готовы" /><Task done title="Главная страница" text="Добавлены заголовок, текст и кнопка" /><Task done title="Предпросмотр" text="Приложение корректно выглядит на телефоне" /><Task title="Настроить форму" text="Укажите, куда отправлять новые заявки" action="Настроить" onClick={onEdit} /><Task title="Подключить Telegram-бота" text="Понадобится токен от @BotFather" action="Подключить" onClick={onLaunch} /></div>
        <div className="right-column"><div className="panel preview-card"><div className="panel-title"><div><span>ВАШЕ ПРИЛОЖЕНИЕ</span><h2>Главная</h2></div><span className="draft-pill">Черновик</span></div><div className="small-preview"><div><b>Добро пожаловать!</b><p>Расскажите клиентам, чем вы можете им помочь.</p><button>Оставить заявку</button></div></div><div className="preview-actions"><button className="outline-button" onClick={onEdit}><Eye />Предпросмотр</button><button className="outline-button" onClick={onEdit}>Редактировать</button></div></div><div className="panel help-card"><span className="help-avatar">✦</span><div><b>Нужна помощь?</b><p>Проведём по каждому шагу и проверим настройки перед запуском.</p><button>Открыть помощника</button></div></div></div></section>
    </main></div>;
}

function Task({ done, title, text, action, onClick }: { done?: boolean; title: string; text: string; action?: string; onClick?: () => void }) { return <div className={`task ${done ? "done" : ""}`}>{done ? <CheckCircle2 /> : <Circle />}<div><b>{title}</b><p>{text}</p></div>{action && <button onClick={onClick}>{action}<ChevronRight /></button>}</div>; }
